title: Joonhyeok Ahn
description: ê¸€ì“°ëŠ” ê°œë°œì (ê¸€ê°œ)ğŸ‡ºğŸ‡¸ğŸ‡°ğŸ‡· This is the document of my journey as a software engineer. I love to talk about software engineering, AI, notes, deep work. 
theme: jekyll-theme-minimal
